### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by Ali-sharafi-git** [cyntler/react-doc-viewer#160]
Hi 
Thanks for the effort you are putting on this package. 
Im trying to build my Next JS project which uses this package and I get the following error. Can you please help me to fix

```
ReferenceError: window is not defined
    at C:\Work\DryKISS\nx-services\node_modules\pdfjs-dist\lib\web\ui_utils.js:564:3
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Work\DryKISS\nx-services\node_modules\pdfjs-dist\lib\web\ui_utils.js:563:26)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Work\DryKISS\nx-services\node_modules\pdfjs-dist\lib\web\pdf_link_service.js:29:17)  
Node.js v18.16.0
```

I have added following check on top of my component but not helping 
```
if (typeof window === 'undefined') {
    return null
  }
```

**Comment by ashishsah1000** [comment]
I guess this should be
```
if (typeof window === undefined) {
    return null
  }
```
It did not worked for me.
When I was using `react-doc-viewer` then I faced this issue. I removed that one by `npm remove react-doc-viewer` and then installed this one `npm i @cyntler/react-doc-viewer` this solved my issue. The build was also created successfully.

**Comment by cyntler** [comment]
@Ali-sharafi-git Looks like problem in the `pdfjs-dist` library. I think, you have to render library's component only on the browser side. Maybe your:

```
if (typeof window === 'undefined') {
    return null
  }
```

is not in the right place. Paste more of your code here.
