### ISSUE TITLE
DataStream is not defined

### ISSUE THREAD

**Issue by abdurrahimkh** [cyntler/react-doc-viewer#28]
Hi i am facing issue when using this library it is show me following error when i follow the first example in docs

Uncaught ReferenceError: DataStream is not defined
    at DataStream.js:24:5
    at DataStream.js:17:26
    at node_modules/wl-msg-reader/lib/DataStream.js (DataStream.js:22:1)
    at __require2 (chunk-UOOVSGC4.js?v=2d8e5a12:18:50)
    at node_modules/wl-msg-reader/index.js (index.js:3:22)
    at __require2 (chunk-UOOVSGC4.js?v=2d8e5a12:18:50)
    at node_modules/@cyntler/react-doc-viewer/dist/plugins/msg/index.js (index.js:36:23)
    at __require2 (chunk-UOOVSGC4.js?v=2d8e5a12:18:50)
    at node_modules/@cyntler/react-doc-viewer/dist/index.js (index.js:62:29)
    at __require2 (chunk-UOOVSGC4.js?v=2d8e5a12:18:50)

**Comment by cyntler** [comment]
@abdurrahimkh The same problem was at the original source code. The issue: https://github.com/Alcumus/react-doc-viewer/issues/91.

Following the latest comment of the above issue - I added the same to this fork: https://github.com/cyntler/react-doc-viewer/pull/31.

**Comment by vmontoyarugertek** [comment]
Good day, the error keeps appearing as soon as one installs and implements the library. the version is     "react-doc-viewer": "^0.1.5",

**Comment by cyntler** [comment]
@vmontoyarugertek Hey! Ok but this is a fork of `react-doc-viewer`. To install this library you have to follow a new readme. This fork is able to install as `@cyntler/react-doc-viewer`.
